dtb-y += $(subst ",,$(CONFIG_MSTAR_CHIP_NAME)_an).dtb
dtb-y += $(subst ",,$(CONFIG_MSTAR_CHIP_NAME)_ramdisk).dtb

dtb-$(CONFIG_MSTAR_M7322) += m7322_an_midgard.dtb
dtb-$(CONFIG_MSTAR_M7322) += m7322_an_avb.dtb
dtb-$(CONFIG_MSTAR_M7322) += m7322_an.main_dtb
dtb-$(CONFIG_MSTAR_M7322) += m7322_overlay_1.dtbo
dtb-$(CONFIG_MSTAR_M7322) += m7322_overlay_28.dtbo
dtb-$(CONFIG_MSTAR_M7322) += m7322_overlay_avb28.dtbo

dtb-$(CONFIG_MSTAR_M7632) += \
	m7632_an_avb.dtb \
	m7632_an.main_dtb \
	m7632_an_midgard.dtb \
	m7632_overlay_28.dtbo \
	m7632_overlay_avb28.dtbo \
	m7632_MediaTek_m7632_MTV19006.dtb \
	m7632_MediaTek_m7632_MTV19008.dtb \
	m7632_MediaTek_m7632_MT164B.dtb

dtb-$(CONFIG_MSTAR_M7332) += \
	m7332_an_avb.dtb \
	m7332_an.main_dtb \
	m7332_overlay.dtbo \
	m7332_overlay_28.dtbo \
	m7332_overlay_dp_28.dtbo \
	m7332_overlay_avb28.dtbo \
	m7332_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT165B.dtb \
	m7332_MediaTek_m7332_MT168B.dtb \
	m7332_MediaTek_m7332_MT169B-2K.dtb \
	m7332_MediaTek_m7332_MT169B-4K.dtb \
	m7332_MediaTek_m7332_MTV19007.dtb \
	m7332_MediaTek_m7332_MTV19013.dtb \
	m7332_MediaTek_m7332_MT165B_avb.dtb \
	m7332_MediaTek_m7332_MT165B_overlay.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp.dtbo \
	m7332_MediaTek_m7332_MT168B_avb.dtb \
	m7332_MediaTek_m7332_MT168B_overlay.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_ledblink.dtbo \
	m7332_overlay_28_ledblink.dtbo \
	m7332_overlay_avb28_ledblink.dtbo \
	m7332_overlay_dp_28_ledblink.dtbo \
	m7332_overlay_dp_avb28_ledblink.dtbo \
	m7332_overlay_ledblink.dtbo \
	m7332_SW_SW4_TG_MT165B.dtb \
	m7332_SW_SW4_TG_MT165B_avb.dtb \
	m7332_SW_SW4_TG_MT165B_overlay_dp_avb28.dtbo \
	m7332_SW_SW4_TG_MT165B_overlay_avb28.dtbo \
	m7332_SW_SW4H_B_MT165B.dtb \
	m7332_SW_SW4H_B_MT165B_avb.dtb \
	m7332_SW_SW4H_B_MT165B_overlay_dp_avb28.dtbo \
	m7332_SW_SW4H_B_MT165B_overlay_avb28.dtbo \
	m7332_SW_SW4H_N_MT165B.dtb \
	m7332_SW_SW4H_N_MT165B_avb.dtb \
	m7332_SW_SW4H_N_MT165B_overlay_dp_avb28.dtbo \
	m7332_SW_SW4H_N_MT165B_overlay_avb28.dtbo \
    m7332_SW_SW4H_H_MT165B.dtb \
    m7332_SW_SW4H_H_MT165B_avb.dtb \
    m7332_SW_SW4H_H_MT165B_overlay_dp_avb28.dtbo \
    m7332_SW_SW4H_H_MT165B_overlay_avb28.dtbo \
	m7332_SW_SW4H_FF_TG_MT165B.dtb \
	m7332_SW_SW4H_FF_TG_MT165B_avb.dtb \
	m7332_SW_SW4H_FF_TG_MT165B_overlay_dp_avb28.dtbo \
	m7332_SW_SW4H_FF_TG_MT165B_overlay_avb28.dtbo \
	m7332_SW_SW4H_FF_B_MT165B.dtb \
	m7332_SW_SW4H_FF_B_MT165B_avb.dtb \
	m7332_SW_SW4H_FF_B_MT165B_overlay_dp_avb28.dtbo \
	m7332_SW_SW4H_FF_B_MT165B_overlay_avb28.dtbo \
	m7332_SW_SW4H_FF_N_MT165B.dtb \
	m7332_SW_SW4H_FF_N_MT165B_avb.dtb \
	m7332_SW_SW4H_FF_N_MT165B_overlay_dp_avb28.dtbo \
	m7332_SW_SW4H_FF_N_MT165B_overlay_avb28.dtbo \
    m7332_SW_SW4H_W_MT165B.dtb \
    m7332_SW_SW4H_W_MT165B_avb.dtb \
    m7332_SW_SW4H_W_MT165B_overlay_dp_avb28.dtbo \
    m7332_SW_SW4H_W_MT165B_overlay_avb28.dtbo \
    m7332_Panasonic_SW4H_PANATV_MT165B.dtb \
    m7332_Panasonic_SW4H_PANATV_MT165B_avb.dtb \
    m7332_Panasonic_SW4H_PANATV_MT165B_overlay_dp_avb28.dtbo \
    m7332_Panasonic_SW4H_PANATV_MT165B_overlay_avb28.dtbo \
    m7332_SW_SW4H_FF_H_MT165B.dtb \
    m7332_SW_SW4H_FF_H_MT165B_avb.dtb \
    m7332_SW_SW4H_FF_H_MT165B_overlay_dp_avb28.dtbo \
    m7332_SW_SW4H_FF_H_MT165B_overlay_avb28.dtbo \
    m7332_SW_SW4H_FF_W_MT165B.dtb \
    m7332_SW_SW4H_FF_W_MT165B_avb.dtb \
    m7332_SW_SW4H_FF_W_MT165B_overlay_dp_avb28.dtbo \
    m7332_SW_SW4H_FF_W_MT165B_overlay_avb28.dtbo

dtb-$(CONFIG_MSTAR_M7642) += \
	m7642_MediaTek_m7642_MTV19020.dtb \
	m7642_MediaTek_m7642_MTV19024.dtb \
	m7642_MediaTek_m7642_MT166B.dtb \
	m7642_an_avb.dtb \
	m7642_an.main_dtb \
	m7642_overlay_28.dtbo \
	m7642_overlay_dp_28.dtbo \
	m7642_overlay_avb28.dtbo \
	m7642_overlay_dp_avb28.dtbo \
	m7642_an_midgard.dtb

dtb-$(CONFIG_MSTAR_MT5862) += \
	mt5862_an_avb.dtb \
	mt5862_an.main_dtb \
	mt5862_overlay_28.dtbo \
	mt5862_overlay_avb28.dtbo 

